package rules

 //Seçili üründe %x indirim kampanyası
 //Seçili üründe xTL indirim kampanyası

import com.javainuse.model.Product;
import com.javainuse.model.Order;
import com.javainuse.model.Payment;
import com.javainuse.model.Discount;
import com.javainuse.model.ProductCategory;
import com.javainuse.model.Campaign;
import com.javainuse.model.OrderItem;
import com.javainuse.model.ProductGroup;


import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.lang.Double;

//%x indirim kampanyası
rule "Discount by percentage"
	when
		orderObject: Order()
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "percent") from $eligbleCampaigns
        $campaign : Campaign(name == "%x indirim kampanyası") from $eligbleCampaigns

	then
	    for(OrderItem orderItem : orderObject.getOrderItems()) {
	        Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = itemPrice * $campaign.getBenefit().getDiscount().getAmount()/100;

            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                                new Discount(
                                                                    $campaign.getBenefit().getDiscount().getType(),
                                                                    itemDiscount
                                                                    ),
                                                                itemPrice,
                                                                itemPrice - itemDiscount
                                                               ),
                                                            $campaign
                                                               ));
                System.out.println(     "Campaign: "            + $campaign.getName()
                                      + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                      + " Item Discount:"       + itemDiscount
                                      + " Item Price: "         + itemPrice
                                      + " Final Price: "        + (itemPrice - itemDiscount));
	    }


        System.out.println("\n\n\n");
	end


//xTL indirim kampanyası
rule "Discount by amount"
	when
		orderObject: Order()
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash   ") from $eligbleCampaigns
        $campaign : Campaign(name == "xTL indirim kampanyası") from $eligbleCampaigns

	then
        int availableItemSize = orderObject.getOrderItems().size();
        for(OrderItem orderItem : orderObject.getOrderItems()) {
            Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                                new Discount(
                                                                    $campaign.getBenefit().getDiscount().getType(),
                                                                    itemDiscount
                                                                    ),
                                                                itemPrice,
                                                                itemPrice - itemDiscount
                                                               ),
                                                            $campaign
                                                               ));
                System.out.println(     "Campaign: "            + $campaign.getName()
                                      + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                      + " Item Discount:"       + itemDiscount
                                      + " Item Price: "         + itemPrice
                                      + " Final Price: "        + (itemPrice - itemDiscount));
        }
        System.out.println("\n\n\n");

	end

// Seçili üründe %x indirim kampanyası
rule "Discount by percentage on certain products"
    when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili üründe %x indirim kampanyası") from $eligbleCampaigns
        orderObject : Order()
        $orderItem : OrderItem() from orderObject.orderItems
        $hash : HashMap() from $campaign.parameters.get("products")
        $products: ArrayList() from collect (Product(name == $orderItem.product.name) from $hash.values())
        $product : Product() from $products
    then

        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = itemPrice * $campaign.getBenefit().getDiscount().getAmount()/100;
        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            itemPrice - itemDiscount
                                                           ),
                                                        $campaign
                                                           ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + (itemPrice - itemDiscount));
        System.out.println("\n\n\n");
    end

// Seçili üründe xTL indirim kampanyası
rule "Discount by cash on certain products"
    when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili üründe xTL indirim kampanyası") from $eligbleCampaigns
        orderObject : Order()
        $orderItem : OrderItem() from orderObject.orderItems
        $hash : HashMap() from $campaign.parameters.get("products")
        $products: ArrayList() from collect (Product(name == $orderItem.product.name) from $hash.values())
        $product : Product() from $products
	then
        int availableItemSize = $products.size();
        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            itemPrice - itemDiscount
                                                           ),
                                                        $campaign
                                                           ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + (itemPrice - itemDiscount));
        System.out.println("\n\n\n");
    end


// Kredi kartı ödemelerinde %x indirim kampanyası
rule "Discount by percentage on credit card payment"
    when
        orderObject : Order(paymentType.type == "credit")
        $eligbleCampaigns : ArrayList()
        // $campaign : Campaign(benefit.discount.type == "percent") from $eligbleCampaigns
        $campaign : Campaign(name == "Kredi kartı ödemelerinde %x indirim kampanyası") from $eligbleCampaigns
    then

        for(OrderItem orderItem : orderObject.getOrderItems()) {

            Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = itemPrice * $campaign.getBenefit().getDiscount().getAmount()/100;

            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            itemPrice - itemDiscount
                                                           ),
                                                    $campaign
                                                           ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + (itemPrice - itemDiscount));
        }

        System.out.println("\n\n\n");
    end

// Nakit ödemelerde xTL indirim kampanyası
rule "Discount by cash on cash payment"
    when
        orderObject : Order(paymentType.type == "cash")
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash") from $eligbleCampaigns
        $campaign : Campaign(name == "Nakit ödemelerde xTL indirim kampanyası") from $eligbleCampaigns
    then
        int availableItemSize = orderObject.getOrderItems().size();
        for(OrderItem orderItem : orderObject.getOrderItems()) {

            Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

            //sum += orderItem.getProduct().getPrice();
            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            itemPrice - itemDiscount
                                                               ),
                                                        $campaign
                                                               ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + (itemPrice - itemDiscount));
        }
        System.out.println("\n\n\n");
    end

// Seçili ürün kategorilerinde %x indirim kampanyası
rule "Discount by percentage on certain product categories"
    when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili ürün kategorilerinde %x indirim kampanyası") from $eligbleCampaigns
        orderObject : Order()
        //$orderItems: ArrayList() from collect($item: OrderItem() from orderObject.orderItems)
        $hash : HashMap() from $campaign.parameters.get("categories")
        $categories: ArrayList() from collect (ProductCategory() from $hash.values())
        $category : ProductCategory() from $categories
        $orderItem : OrderItem($product: product.categories contains $category) from orderObject.orderItems
        // $campaign : Campaign(benefit.discount.type == "percent") from $eligbleCampaigns
    then
        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = itemPrice * $campaign.getBenefit().getDiscount().getAmount()/100;

        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                        new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                        itemPrice,
                                                        itemPrice - itemDiscount
                                                         ),
                                                        $campaign
                                                           ));

        System.out.println(     "Campaign: "            + $campaign.getName()
                              + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                              + " Item Discount:"       + itemDiscount
                              + " Item Price: "         + itemPrice
                              + " Final Price: "        + (itemPrice - itemDiscount));
        System.out.println("\n\n\n");
    end

// Seçili ürün kategorilerinde xTL indirim kampanyası
rule "Discount by cash on certain product categories"
    when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili ürün kategorilerinde xTL indirim kampanyası") from $eligbleCampaigns
        orderObject : Order()
        $hash : HashMap() from $campaign.parameters.get("categories")
        $categories: ArrayList() from collect (ProductCategory() from $hash.values())
        $category : ProductCategory() from $categories
        $ordeItems: ArrayList() from  collect (OrderItem($product: product.categories contains $category) from orderObject.orderItems)
        $orderItem: OrderItem() from $ordeItems
	then
        int availableItemSize = $ordeItems.size();

        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                        new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                        ),
                                                        itemPrice,
                                                        itemPrice - itemDiscount
                                                         ),
                                                        $campaign
                                                           ));

        System.out.println(     "Campaign: "            + $campaign.getName()
                              + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                              + " Item Discount:"       + itemDiscount
                              + " Item Price: "         + itemPrice
                              + " Final Price: "        + (itemPrice - itemDiscount));
        System.out.println("\n\n\n");
    end


// TODO: Kontrol et
// Seçili ürünlerde x puan indirim kampanyası
rule "Discount by point on certain products"
    when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili ürünlerde x puan indirim kampanyası") from $eligbleCampaigns
        orderObject : Order()
        $eligbleProducts : ArrayList()
        $orderItem : OrderItem() from orderObject.orderItems
        $hash : HashMap() from $campaign.parameters.get("products")
        $products: ArrayList() from collect (Product(name == $orderItem.product.name) from $hash.values())
        $product : Product() from $products
	then
        int availableItemSize = $products.size();
        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            // TODO: puan çevirim
                                                            itemPrice
                                                           ),
                                                        $campaign
                                                           ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + itemPrice
                                  + " Item Point: "         + itemDiscount);
        System.out.println("\n\n\n");
    end

// Seçili ürün kategorilerinde x puan indirim kampanyası
rule "Discount by point on certain product categories"
    when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili ürün kategorilerinde x puan indirim kampanyası") from $eligbleCampaigns
        orderObject : Order()
        $hash : HashMap() from $campaign.parameters.get("categories")
        $categories: ArrayList() from collect (ProductCategory() from $hash.values())
        $category : ProductCategory() from $categories
        $ordeItems: ArrayList() from  collect (OrderItem($product: product.categories contains $category) from orderObject.orderItems)
        $orderItem: OrderItem() from $ordeItems
	then
        int availableItemSize = $ordeItems.size();

        Double itemPrice = $orderItem.getProduct().getPrice();
        // TODO: puan çevirim
        Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            // TODO: puan çevirim
                                                            itemPrice
                                                           ),
                                                        $campaign
                                                           ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + itemPrice
                                  + " Item Point: "         + itemDiscount);
        System.out.println("\n\n\n");
    end

// ---------------- Baremli ---------------------

// xTL üzeri alışverişe özel ytl puan kampanyası
rule "Discount by point over limit"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "xTL üzeri alışverişe özel ytl puan kampanyası") from $eligbleCampaigns
		orderObject: Order(paymentType.totalAmount > $campaign.limit)
	then
        int availableItemSize = orderObject.getOrderItems().size();
        for(OrderItem orderItem : orderObject.getOrderItems()) {
            Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;
            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                                new Discount(
                                                                    $campaign.getBenefit().getDiscount().getType(),
                                                                    itemDiscount
                                                                    ),
                                                                itemPrice,
                                                                // TODO: puan çevirim
                                                                itemPrice
                                                               ),
                                                            $campaign
                                                               ));
                System.out.println(     "Campaign: "            + $campaign.getName()
                                      + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                      + " Item Discount:"       + itemDiscount
                                      + " Item Price: "         + itemPrice
                                      + " Final Price: "        + itemPrice
                                      + " Item Point: "         + itemDiscount);
        }
        System.out.println("\n\n\n");

	end

//xTL üzeri alışverişe özel ytl indirim kampanyası
rule "Discount by cash over limit"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "xTL üzeri alışverişe özel ytl indirim kampanyası") from $eligbleCampaigns
		orderObject: Order(paymentType.totalAmount > $campaign.limit)
	then
        int availableItemSize = orderObject.getOrderItems().size();
        for(OrderItem orderItem : orderObject.getOrderItems()) {
            Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                                new Discount(
                                                                    $campaign.getBenefit().getDiscount().getType(),
                                                                    itemDiscount
                                                                    ),
                                                                itemPrice,
                                                                itemPrice - itemDiscount
                                                               ),
                                                            $campaign
                                                               ));
                System.out.println(     "Campaign: "            + $campaign.getName()
                                      + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                      + " Item Discount:"       + itemDiscount
                                      + " Item Price: "         + itemPrice
                                      + " Final Price: "        + (itemPrice - itemDiscount));
        }
        System.out.println("\n\n\n");

	end



//xTL üzeri alışverişe özel %y puan kampanyası
rule "Discount by percent point over limit"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "xTL üzeri alışverişe özel %y puan kampanyası") from $eligbleCampaigns
		orderObject: Order(paymentType.totalAmount > $campaign.limit)
	then

        for(OrderItem orderItem : orderObject.getOrderItems()) {
            Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = itemPrice * $campaign.getBenefit().getDiscount().getAmount()/100;

            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                                new Discount(
                                                                    $campaign.getBenefit().getDiscount().getType(),
                                                                    itemDiscount
                                                                    ),
                                                                itemPrice,
                                                                // TODO: puan çevirim
                                                                itemPrice
                                                               ),
                                                            $campaign
                                                               ));
                System.out.println(     "Campaign: "            + $campaign.getName()
                                      + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                      + " Item Discount:"       + itemDiscount
                                      + " Item Price: "         + itemPrice
                                      + " Final Price: "        + itemPrice
                                      + " Item Point: "         + itemDiscount);
        }
        System.out.println("\n\n\n");

	end

//xTL üzeri kredi kartı ödemelerine özel yTL indirim kampanyası
rule "Discount by cash over limit and credit"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "xTL üzeri kredi kartı ödemelerine özel yTL indirim kampanyası") from $eligbleCampaigns
		orderObject: Order(paymentType.totalAmount > $campaign.limit, paymentType.type == "credit")
	then
        int availableItemSize = orderObject.getOrderItems().size();
        for(OrderItem orderItem : orderObject.getOrderItems()) {
            Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                                new Discount(
                                                                    $campaign.getBenefit().getDiscount().getType(),
                                                                    itemDiscount
                                                                    ),
                                                                itemPrice,
                                                                itemPrice - itemDiscount
                                                               ),
                                                            $campaign
                                                               ));
                System.out.println(     "Campaign: "            + $campaign.getName()
                                      + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                      + " Item Discount:"       + itemDiscount
                                      + " Item Price: "         + itemPrice
                                      + " Final Price: "        + (itemPrice - itemDiscount));
        }
        System.out.println("\n\n\n");

	end

//xTL nakit ödemelere özel %y indirim kampanyası
rule "Discount by percent over limit and credit"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "xTL nakit ödemelere özel %y indirim kampanyası") from $eligbleCampaigns
		orderObject: Order(paymentType.totalAmount > $campaign.limit, paymentType.type == "cash")
	then
	    for(OrderItem orderItem : orderObject.getOrderItems()) {
	        Double itemPrice = orderItem.getProduct().getPrice();
            Double itemDiscount = itemPrice * $campaign.getBenefit().getDiscount().getAmount()/100;

            orderObject.getSimulatedPaymentOptions().add(new OrderItem(orderItem.getProduct(),
                                                        new Payment(orderObject.getPaymentType().getType(),
                                                                new Discount(
                                                                    $campaign.getBenefit().getDiscount().getType(),
                                                                    itemDiscount
                                                                    ),
                                                                itemPrice,
                                                                itemPrice - itemDiscount
                                                               ),
                                                            $campaign
                                                               ));
                System.out.println(     "Campaign: "            + $campaign.getName()
                                      + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                      + " Item Discount:"       + itemDiscount
                                      + " Item Price: "         + itemPrice
                                      + " Final Price: "        + (itemPrice - itemDiscount));
	    }
        System.out.println("\n\n\n");

	end

// TODO: Buraya bak, Toplam tutar mı yoksa grup tutarı mı?
//Seçili ürün gruplarında xTL üzeri alışverişe özel ytl puan kampanyası
rule "Discount by point over limit and credit for certain groups"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili ürün gruplarında xTL üzeri alışverişe özel ytl puan kampanyası") from $eligbleCampaigns
        $hash : HashMap() from $campaign.parameters.get("groups")
        $groups: ArrayList() from collect (ProductGroup() from $hash.values())
        $group : ProductGroup() from $groups
		orderObject: Order(paymentType.totalAmount > $campaign.limit)
        $ordeItems: ArrayList() from  collect (OrderItem($product: product.groups contains $group)from orderObject.orderItems)
        $orderItem: OrderItem() from $ordeItems
	then
        int availableItemSize = $ordeItems.size();
        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;
        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            // TODO: puan çevirim
                                                            itemPrice
                                                           ),
                                                        $campaign
                                                           ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + itemPrice
                                  + " Item Point: "         + itemDiscount);

        System.out.println("\n\n\n");



	end



//Seçili ürün gruplarında xTL üzeri alışverişe özel ytl indirim kampanyası
rule "Discount by cash over limit for certain groups"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili ürün gruplarında xTL üzeri alışverişe özel ytl indirim kampanyası") from $eligbleCampaigns
        $hash : HashMap() from $campaign.parameters.get("groups")
        $groups: ArrayList() from collect (ProductGroup() from $hash.values())
        $group : ProductGroup() from $groups
        orderObject: Order(paymentType.totalAmount > $campaign.limit)
        $ordeItems: ArrayList() from  collect (OrderItem($product: product.groups contains $group)from orderObject.orderItems)
        $orderItem: OrderItem() from $ordeItems
	then
//        //Long availableItemSize = orderObject.getOrderItems().stream().filter(orderItem -> $eligbleGroups.stream().anyMatch(t -> orderItem.getProduct().getGroups().stream().map(ProductGroup::getType).anyMatch(x -> x.equals(((ProductGroup)t).getType())))).count();
//        List<OrderItem> collection = new ArrayList<>();
//        for (OrderItem item : orderObject.getOrderItems()){
//            for (Object group : $eligbleGroups){
//                ProductGroup currentGroup = (ProductGroup) group;
//                if (item.getProduct().getGroups().contains(currentGroup)) collection.add(item);
//            }
//        }
//        int availableItemSize = collection.size();
        int availableItemSize = $ordeItems.size();

        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = $campaign.getBenefit().getDiscount().getAmount() / availableItemSize;

        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                        new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                        ),
                                                        itemPrice,
                                                        itemPrice - itemDiscount
                                                         ),
                                                        $campaign
                                                           ));

        System.out.println(     "Campaign: "            + $campaign.getName()
                              + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                              + " Item Discount:"       + itemDiscount
                              + " Item Price: "         + itemPrice);
        System.out.println("\n\n\n");


	end

//Seçili ürün gruplarında xTL üzeri alışverişe özel %y indirim kampanyası
rule "Discount by percent over limit  for certain groups"
	when
        $eligbleCampaigns : ArrayList()
        $campaign : Campaign(name == "Seçili ürün gruplarında xTL üzeri alışverişe özel ytl puan kampanyası") from $eligbleCampaigns
        $hash : HashMap() from $campaign.parameters.get("groups")
        $groups: ArrayList() from collect (ProductGroup() from $hash.values())
        $group : ProductGroup() from $groups
        orderObject: Order(paymentType.totalAmount > $campaign.limit)
        $ordeItems: ArrayList() from  collect (OrderItem($product: product.groups contains $group)from orderObject.orderItems)
        $orderItem: OrderItem() from $ordeItems
	then
        Double itemPrice = $orderItem.getProduct().getPrice();
        Double itemDiscount = itemPrice * $campaign.getBenefit().getDiscount().getAmount()/100;

        orderObject.getSimulatedPaymentOptions().add(new OrderItem($orderItem.getProduct(),
                                                    new Payment(orderObject.getPaymentType().getType(),
                                                            new Discount(
                                                                $campaign.getBenefit().getDiscount().getType(),
                                                                itemDiscount
                                                                ),
                                                            itemPrice,
                                                            itemPrice - itemDiscount
                                                           ),
                                                        $campaign
                                                           ));
            System.out.println(     "Campaign: "            + $campaign.getName()
                                  + " Benefit Discount: "   + $campaign.getBenefit().getDiscount()
                                  + " Item Discount:"       + itemDiscount
                                  + " Item Price: "         + itemPrice
                                  + " Final Price: "        + (itemPrice - itemDiscount));

        System.out.println("\n\n\n");

	end