package rules

 //Seçili üründe %x indirim kampanyası
 //Seçili üründe xTL indirim kampanyası

import com.javainuse.model.Product;
import com.javainuse.model.Order;
import com.javainuse.model.Payment;
import com.javainuse.model.Discount;
import com.javainuse.model.ProductCategory;
import com.javainuse.model.Campaign;

import com.javainuse.service.JewelleryShopService;
import java.util.ArrayList;
import java.util.List;

//%x indirim kampanyası
rule "Discount by percentage"
	when
		orderObject: Order()
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "percent") from $eligbleCampaigns
        $campaign : Campaign(name == "%x indirim kampanyası") from $eligbleCampaigns
	then
        orderObject.getSimulatedPaymentOptions().add
        (new Payment
            (orderObject.getPaymentType(), $campaign.getBenefit().getDiscount(), orderObject.getProduct().getPrice(),
                orderObject.getProduct().getPrice()*(1-($campaign.getBenefit().getDiscount().getAmount())/100)
            )
         );
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
	end


//xTL indirim kampanyası
rule "Discount by amount"
	when
		orderObject: Order()
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash") from $eligbleCampaigns
        $campaign : Campaign(name == "xTL indirim kampanyası") from $eligbleCampaigns
	then
		orderObject.getSimulatedPaymentOptions().add
		(new Payment
		    (orderObject.getPaymentType(), $campaign.getBenefit().getDiscount(), orderObject.getProduct().getPrice(),
                orderObject.getProduct().getPrice()-($campaign.getBenefit().getDiscount().getAmount())
            )
        );
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());;
	end

// Seçili üründe %x indirim kampanyası
rule "Discount by percentage on certain products"
    when
        orderObject : Order()
        $eligbleProducts : ArrayList()
        $product : Product(name == orderObject.product.name) from $eligbleProducts
        $eligbleCampaigns : ArrayList()
        // $campaign : Campaign(benefit.discount.type == "percent") from $eligbleCampaigns
        $campaign : Campaign(name == "Seçili üründe %x indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(), $campaign.getBenefit().getDiscount(), orderObject.getProduct().getPrice(), orderObject.getProduct().getPrice()*(1-($campaign.getBenefit().getDiscount().getAmount())/100)));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end

// Seçili üründe xTL indirim kampanyası
rule "Discount by cash on certain products"
    when
        orderObject : Order()
        $eligbleProducts : ArrayList()
        $product : Product(name == orderObject.product.name) from $eligbleProducts
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash") from $eligbleCampaigns
        $campaign : Campaign(name == "Seçili üründe xTL indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(),
                                                    $campaign.getBenefit().getDiscount(),
                                                    orderObject.getProduct().getPrice(),
                                                    orderObject.getProduct().getPrice()-($campaign.getBenefit().getDiscount().getAmount())));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end


// Kredi kartı ödemelerinde %x indirim kampanyası
rule "Discount by percentage on credit card payment"
    when
        orderObject : Order(paymentType == "credit")
        $eligbleCampaigns : ArrayList()
        // $campaign : Campaign(benefit.discount.type == "percent") from $eligbleCampaigns
        $campaign : Campaign(name == "Kredi kartı ödemelerinde %x indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(), $campaign.getBenefit().getDiscount(), orderObject.getProduct().getPrice(), orderObject.getProduct().getPrice()*(1-($campaign.getBenefit().getDiscount().getAmount())/100)));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end

// Nakit ödemelerde xTL indirim kampanyası
rule "Discount by cash on cash payment"
    when
        orderObject : Order(paymentType == "cash")
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash") from $eligbleCampaigns
        $campaign : Campaign(name == "Nakit ödemelerde xTL indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(),
                                                    $campaign.getBenefit().getDiscount(),
                                                    orderObject.getProduct().getPrice(),
                                                    orderObject.getProduct().getPrice()-($campaign.getBenefit().getDiscount().getAmount())));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end

// Seçili ürün kategorilerinde %x indirim kampanyası
rule "Discount by percentage on certain product categories"
    when
        orderObject : Order()
        $eligbleCategories : ArrayList()
        $category : ProductCategory(type == orderObject.product.category.type) from $eligbleCategories
        $eligbleCampaigns : ArrayList()
        // $campaign : Campaign(benefit.discount.type == "percent") from $eligbleCampaigns
        $campaign : Campaign(name == "Seçili ürün kategorilerinde %x indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(), $campaign.getBenefit().getDiscount(), orderObject.getProduct().getPrice(), orderObject.getProduct().getPrice()*(1-($campaign.getBenefit().getDiscount().getAmount())/100)));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end

// Seçili ürün kategorilerinde xTL indirim kampanyası
rule "Discount by cash on certain product categories"
    when
        orderObject : Order()
        $eligbleCategories : ArrayList()
        $category : ProductCategory(type == orderObject.product.category.type) from $eligbleCategories
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash") from $eligbleCampaigns
        $campaign : Campaign(name == "Seçili ürün kategorilerinde xTL indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(),
                                                    $campaign.getBenefit().getDiscount(),
                                                    orderObject.getProduct().getPrice(),
                                                    orderObject.getProduct().getPrice()-($campaign.getBenefit().getDiscount().getAmount())));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end


// TODO: Kontrol et
// Seçili ürünlerde x puan indirim kampanyası
rule "Discount by point on certain products"
    when
        orderObject : Order()
        $eligbleProducts : ArrayList()
        $product : Product(name == orderObject.product.name) from $eligbleProducts
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash") from $eligbleCampaigns
        $campaign : Campaign(name == "Seçili ürünlerde x puan indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(),
                                                    $campaign.getBenefit().getDiscount(),
                                                    orderObject.getProduct().getPrice(),
                                                    orderObject.getProduct().getPrice()));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end

// Seçili ürün kategorilerinde x puan indirim kampanyası
rule "Discount by point on certain product categories"
    when
        orderObject : Order()
        $eligbleCategories : ArrayList()
        $category : ProductCategory(type == orderObject.product.category.type) from $eligbleCategories
        $eligbleCampaigns : ArrayList()
        //$campaign : Campaign(benefit.discount.type == "cash") from $eligbleCampaigns
        $campaign : Campaign(name == "Seçili ürün kategorilerinde x puan indirim kampanyası") from $eligbleCampaigns
    then
        orderObject.getSimulatedPaymentOptions().add(new Payment(orderObject.getPaymentType(),
                                                    $campaign.getBenefit().getDiscount(),
                                                    orderObject.getProduct().getPrice(),
                                                    orderObject.getProduct().getPrice()));
        System.out.println("Campaign: " + $campaign.getName() + "...Discount: " + $campaign.getBenefit().getDiscount());
    end

